name: studio_ghibli_app
description: ジブリ作品が一覧として楽しめるアプリです。

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  http: ^0.13.5
  provider: ^6.0.3
  amplify_flutter: ^0.6.6
  amplify_api: ^0.6.6
  cached_network_image: ^3.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
